name: final_proyect
description: "A new Flutter project."
publish_to: 'none'

flutter_inappwebview:
  path: packages/flutter_inappwebview

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: 9.1.1
  url_launcher: ^6.2.4
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_inappwebview: ^6.0.0-beta.25
  geolocator: ^10.0.0
  image_picker: ^1.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/entrega-viaturas-defesa-civil.jpg
    - assets/images/defensa-civil-dominicana-aniversario.jpg
    - assets/images/Algunos voluntarios.jpeg
    - assets/images/Defensa civil logo.png
    - assets/images/FB_IMG.jpg
    - assets/images/proteccion-civil.jpg
    - assets/about/Gilthong.jpg
    - assets/about/Eimi.jpg
    - assets/about/Enmanuel.jpg
    - assets/about/Juan.jpg
    - assets/about/Diorkys.jpg
